=== tiadal/pro-students.de/src/data/courses.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT courses (course*)>

<!ELEMENT course (title, description, contents?, lessons?)>
<!ATTLIST course illustration CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT contents (content+)>
<!ELEMENT content (#PCDATA)>

<!ELEMENT lessons (lesson+)>
<!ELEMENT lesson (#PCDATA)>

=== tiadal/pro-students.de/src/data/courses_for_children.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE courses SYSTEM "courses.dtd">
<courses>

    <course illustration="img/python-logo.svg">
        <title>Introduction to programming in Python</title>
        <description>This course will teach your children how to program in Python</description>
        <contents>
            <content>Installing Python</content>
            <content>Input/Output operations</content>
            <content>Using lists and dictionaries</content>
            <content>Sorting algorithms</content>
            <content>Work with strings</content>
        </contents>
    </course>

    <course illustration="img/photoshop-illustration.svg">
        <title>Introduction to Photoshop</title>
        <description>This course will teach your children how to edit photos with Photoshop.</description>
    </course>

</courses>

=== tiadal/pro-students.de/src/data/courses_for_seniors.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE courses SYSTEM "courses.dtd">
<courses>

    <course illustration="img/basic-computer-usage-illustration.svg">
        <title>How to use a Computer</title>
        <description>This course will help you to start using your computer.</description>
        <lessons>
            <lesson>Basics of using a Computer</lesson>
            <lesson>How to use a Web Browser</lesson>
            <lesson>How to be safe from Computer Viruses and Hackers</lesson>
            <lesson>Using Skype and WhatsApp</lesson>
        </lessons>
    </course>

    <course illustration="img/advanced-computer-usage-illustration.svg">
        <title>Advanced Computer Usage</title>
        <description>This course will teach you how to work with Photoshop as well as the Microsoft Office Suite.</description>
    </course>

</courses>

=== tiadal/pro-students.de/src/data/it_courses_for_companies.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE courses SYSTEM "courses.dtd">
<courses>

    <course illustration="img/spreadsheet.svg">
        <title>Introduction to Excel</title>
        <description>MS Excel is the most popular program for working with tables. In this course we talk about simple data analysis methods, which your employees can use in MS Excel.</description>
    </course>

    <course illustration="img/diagram.svg">
        <title>Introduction to PowerPoint</title>
        <description>MS PowerPoint is an app for creating presentations. We will explain how to work with PowerPoint effectively. This course will show your employees how to create good slides.</description>
    </course>

    <course illustration="img/spreadsheet.svg">
        <title>Introduction to Excel</title>
        <description>MS Excel is the most popular program for working with tables. In this course we talk about simple data analysis methods, which your employees can use in MS Excel.</description>
    </course>

    <course illustration="img/diagram.svg">
        <title>Introduction to PowerPoint</title>
        <description>MS PowerPoint is an app for creating presentations. We will explain how to work with PowerPoint effectively. This course will show your employees how to create good slides.</description>
    </course>

</courses>
